name: Add Two Numbers

on:
  workflow_dispatch:
    inputs:
      num1:
        description: "Enter the first number"
        required: false
        default: "5"
      num2:
        description: "Enter the second number"
        required: true
        default: "3"

      num3:
        description: "Enter the third number"
        required: true
        default: "2"

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Add the two numbers
        env:
          NUM1: ${{ inputs.num1 }}
          NUM2: ${{ inputs.num2 }}
          NUM3: ${{ inputs.num3 }}
        run: |
          echo "First number: $NUM1"
          echo "Second number: $NUM2"
          echo "Third number: $NUM3"
          result=$((NUM1 + NUM2 + NUM3))
          echo "Result: $result"

      - name: Print secret (never do this with real secrets!)
        run: echo "The secret is ${{ secrets.naveen_secret }}"
